### ISSUE TITLE
[PE-D] Tailor to the needs of Uni students

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W15-2/tp#275]
`Dash is tailored to the needs of university students, who must keep track of a slew of different deadlines and commitments`

https://ay2122s1-cs2103t-w15-2.github.io/tp/UserGuide.html

Expected: 
A specialised tasks management tool related to school.

Actual:
Just a general task and contact management system.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: CrownKira/ped#4

**Comment by Zenlzb** [comment]
Not an issue
