### ISSUE TITLE
[PE-D] Tabs not clickable

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W15-2/tp#278]
I don't see the point of having a tab in the GUI when it is not clickable. 

I understand that this is a text-based application, but only being allowed to navigate across tabs using commands is unintuitive and unergonomic :)) 

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: CrownKira/ped#5

**Comment by Zenlzb** [comment]
This is intended. Tab switching is done with 1 letter which makes it faster than clicking
