### ISSUE TITLE
[PE-D] Contact in tasks list 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W15-2/tp#287]
I think this is more of a personal design preference. It seems like the sole purpose of contacts under task is for users to reference when doing assignments.

Expected: 
only tasks in task tab 

Actual: 
contacts again in task tab 

My personal feeling:
TabView might be a poor choice. 

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: CrownKira/ped#6

**Comment by Zenlzb** [comment]
Resolved by #289
