### ISSUE TITLE
[PE-D] Hard to scroll in help page 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W15-2/tp#288]
Too many scrollable regions on the help page might make it hard for users to scroll down. 

Suggestion: 
Make the external scroll region bigger or remove the internal scroll regions

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: CrownKira/ped#7

**Comment by Zenlzb** [comment]
Resolved by #289
