### ISSUE TITLE
[PE-D] Help page text hard to read

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W15-2/tp#296]
Perhaps you can choose a darker colored background ? 

![Screenshot 2021-10-29 at 9.06.43 PM.png](https://raw.githubusercontent.com/CrownKira/ped/main/files/37a962f8-419e-41c8-afa1-a2da8b0a3c83.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: CrownKira/ped#14

**Comment by Zenlzb** [comment]
Resolved by #289
